version: "3.9"

networks:
  transfer_net:
    driver: bridge

services:
  db:
    image: postgres:18.1
    container_name: postgres_db_vlad
    restart: always
    ports:
      - "5019:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer_vlad/postgres:/var/lib/postgresql
    networks:
      - transfer_net
    
  server:
    image: utereskovi/transfer-api-vlad:latest
    container_name: transfer_api_vlad
    volumes:
      - /data/transfer/images:/app/images
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=192.168.64.5;Database=vladDb;Port=5019;Username=vlad;Password=vlad123Dbsecure
    ports:
      - "5020:8080"
    depends_on:
      - db
    networks:
      - transfer_net

  front:
    image: utereskovi/transfer-react-vlad:latest
    container_name: react_front_vlad
    depends_on:
      - server
    ports:
      - "5021:80"
    networks:
      - transfer_net